### ISSUE TITLE
11장. OAuth2로 로그인/로그아웃 구현하기

### ISSUE THREAD

**Issue by hyunmin0317** [hyunmin0317/SpringBoot-Developer#11]

**Comment by hyunmin0317** [comment]
* application-local.yml
```yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 663642..
            client-secret: GOCSP...
            scope:
              - email
              - profile
jwt:
  secret_key: study-springboot
```
